
name: Sync

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: andreiio/rclone-action@v1
      env:
        RCLONE_CONFIG_S3_TYPE: s3
        RCLONE_CONFIG_S3_PROVIDER: Cloudflare
        RCLONE_CONFIG_S3_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        RCLONE_CONFIG_S3_REGION: auto
        RCLONE_CONFIG_S3_ENDPOINT: ${{ secrets.RCLONE_CONFIG_S3_ENDPOINT }}
      with: 
        args:  sync  ./  S3:cdn --exclude /.git*/**  --exclude /*/.gitignore   --progress --exclude .gitignore